### ISSUE TITLE
Showing Error : Couldn't patch librtmp Makefile!

### ISSUE THREAD

**Issue by ddpatel2606** [cine-io/android-ffmpeg-with-rtmp#10]
i am using windows 7 & android-ndk-r8 

when i am compiling it showing this log

agile@agilepc-29 /cygdrive/c/Users/agile/Downloads/android-ffmpeg-with-rtmp-master/android-ffmpeg-with-rtmp-master
$ ./build.sh
Setting up build environment ...
OS_ARCH=cygwin_nt-6.1-x86_64
NDK=d:/android-ndk-windows/android-ndk-r8
SYSROOT=d:/android-ndk-windows/android-ndk-r8/platforms/android-14/arch-arm
TOOLCHAIN=d:/android-ndk-windows/android-ndk-r8/toolchains/arm-linux-androideabi-4.4.3/prebuilt/cygwin_nt-6.1-x86_64
Building openssl-android ...
Building librtmp for android ...
Couldn't patch librtmp Makefile!
Check the build log: /cygdrive/c/Users/agile/Downloads/android-ffmpeg-with-rtmp-master/android-ffmpeg-with-rtmp-master/build/build.log

Please help me 

Thanks,

**Comment by jeffreywescott** [comment]
Hi. These scripts were developed on OS X ... feel free to submit a PR if you get it working on Windows.
