### ISSUE TITLE
Problem /dev/video0 : ioctl(VIDIOC_QUERYCAP): Not a typewriter

### ISSUE THREAD

**Issue by vbx** [cine-io/android-ffmpeg-with-rtmp#11]
Hello, i have a problem with my phone camera. 
Why my camera doesn't work with ffmpeg ?
thx

./ffmpeg -i /dev/video0  -f mpegts udp://192.168.1.52:6000
ffmpeg version git-2014-09-15-3a4aec2 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (GCC)
  configuration: --prefix=/home/vbx/**project**/android-ffmpeg-with-rtmp/src/ffmpeg/android/arm --enable-shared --disable-static --disable-doc --disable-ffplay --disable-ffprobe --disable-ffserver --disable-symver --cross-prefix=/home/vbx/Android/Ndk//toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi- --target-os=linux --arch=arm --enable-cross-compile --enable-librtmp --enable-decoder=h264 --sysroot=/home/vbx/Android/Ndk//platforms/android-19/arch-arm --extra-cflags='-Os -fpic -marm' --extra-ldflags='-L/home/vbx/**project**/android-ffmpeg-with-rtmp/src/openssl-android/libs/armeabi ' --pkg-config=/usr/bin/pkg-config
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 12.100 /  5. 12.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
[video4linux2,v4l2 @ 0x56cf10] ioctl(VIDIOC_QUERYCAP): Not a typewriter
/dev/video0: Not a typewriter

**Comment by jeffreywescott** [comment]
Hi, @vbx ... this project is just a few scripts to _compile_ ffmpeg ... not a support channel for developing with ffmpeg itself. Closing.
