### ISSUE TITLE
Package 'libssl', required by 'librtmp', not found

### ISSUE THREAD

**Issue by rajdeeprath** [cine-io/android-ffmpeg-with-rtmp#12]
Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libssl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libssl', required by 'librtmp', not found
Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing`libssl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libssl', required by 'librtmp', not found
ERROR: librtmp not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

How do i get past this ?

**Comment by jeffreywescott** [comment]
Try installing the `openssl` package fro Homebrew:

``` bash
$ brew install openssl
```
