### ISSUE TITLE
ERROR: librtmp not found using pkg-config

### ISSUE THREAD

**Issue by inkidu** [cine-io/android-ffmpeg-with-rtmp#15]
android-ndk-r10d
Linux localhost.localdomain 3.10.0-229.1.2.el7.x86_64 #1 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.1.1503 (Core)
ERROR: librtmp not found using pkg-config
pkg-config is installed and is version 0.27.1

contents of build/dist/lib
libcrypto.so  librtmp-1.so  libssl.so

**Comment by inkidu** [comment]
same as this issue: https://github.com/cine-io/android-ffmpeg-with-rtmp/issues/12 with the same output in config.log.  openssl is installed on my system.  

libssl.so is located at android-ffmpeg-with-rtmp/src/openssl-andoid/libs/armeabi/libssl.so, but there is no pkgconfig subdirectory or any libssl.pc file.

**Comment by inkidu** [comment]
also the same as https://github.com/cine-io/android-ffmpeg-with-rtmp/issues/4 except pkg-config is installed.  It looks like the user created the .pc file by hand.  I am going to try this fix, as well.

**Comment by inkidu** [comment]
On CentOS:
sudo yum install openssl-devel

achieves that same thing that 
 brew install openssl
does on the MAC

**Comment by MythodeaLoL** [comment]
Android NDK: WARNING:/root/Desktop/master/src/openssl-android/crypto/Android.mk:crypto_static: LOCAL_LDLIBS is always ignored for static libraries  
[armeabi] Install        : libcrypto.so => libs/armeabi/libcrypto.so
[armeabi] Install        : openssl => libs/armeabi/openssl
[armeabi] Install        : libssl.so => libs/armeabi/libssl.so
[armeabi] Install        : ssltest => libs/armeabi/ssltest
patching file Makefile
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file Makefile.rej

**Comment by MythodeaLoL** [comment]
Problem solved, tks @inkidu for info, i love you.

I deleted the master source and downloaded again the android-ffmpeg-with-rtmp-master
try again and work PERFECT. Tks :+1:
