### ISSUE TITLE
Couldn't patch librtmp Makefile!

### ISSUE THREAD

**Issue by doug-samuel** [cine-io/android-ffmpeg-with-rtmp#16]
Hello, I cannot build the android-ffmpeg-with-rtmp because of the following error:

Setting up build environment ...
OS_ARCH=linux-x86_64
NDK=/home/douglas/dev/android-ndk-r10e
SYSROOT=/home/douglas/dev/android-ndk-r10e/platforms/android-19/arch-arm
TOOLCHAIN=/home/douglas/dev/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64
Building openssl-android ...
Building librtmp for android ...
Couldn't patch librtmp Makefile!

Using Ubuntu 14.10 and the build.log is as follows:

Android NDK: WARNING:/home/douglas/dev/android-ffmpeg-with-rtmp/src/openssl-android/crypto/Android.mk:crypto_static: LOCAL_LDLIBS is always ignored for static libraries  
[armeabi] Install        : libcrypto.so => libs/armeabi/libcrypto.so
[armeabi] Install        : openssl => libs/armeabi/openssl
[armeabi] Install        : libssl.so => libs/armeabi/libssl.so
[armeabi] Install        : ssltest => libs/armeabi/ssltest
patching file Makefile
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file Makefile.rej

**Comment by haemi** [comment]
how did you solve this problem?

**Comment by samychen** [comment]
I got the same problem,how did you solve this problem?
